{
 "title": "Multivendor Telemetry",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Nokia SROS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "Node",
   "collapsed": true,
   "panels": [
    {
     "title": "Underlay OSPF Neighbors",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gnmic_sros_ospf_neighbors_neighbor_count{router_router_name=\"Base\", ospf_ospf_instance=\"0\", area_area_id=\"0.0.0.0\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "OSPF Neighbors Uptime",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gnmic_sros_ospf_uptime_up_time{router_router_name=\"Base\", ospf_ospf_instance=\"0\", area_area_id=\"0.0.0.0\"} / 100",
       "legendFormat": "{{neighbor_state_router_id}}"
      }
     ]
    },
    {
     "title": "Overlay BGP Neighbors",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 11, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gnmic_sros_bgp_peers_peers{router_router_name=\"Base\"}",
       "legendFormat": "Total Peers"
      },
      {
       "expr": "count(gnmic_sros_bgp_neighbors_sent{router_router_name=\"Base\"} > 0)",
       "legendFormat": "Up Peers"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "gnmic_sros_cpu_cpu_usage", "legendFormat": "Total" }
     ]
    },
    {
     "title": "Trhoughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(gnmic_sros_if_stats_in_octets[$__rate_interval])*8",
       "legendFormat": "{{port_port_id}}:IN"
      },
      {
       "expr": "rate(gnmic_sros_if_stats_out_octets[$__rate_interval])*8",
       "legendFormat": "{{port_port_id}}:OUT"
      }
     ]
    },
    {
     "title": "Interface Operational Status",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 5, "x": 7, "y": 8 },
     "targets": [
      {
       "expr": "gnmic_sros_if_oper_state_oper_state",
       "legendFormat": "{{port_port_id}}"
      }
     ]
    },
    {
     "title": "BGP Routes",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gnmic_sros_bgp_neighbors_received{router_router_name=\"Base\"})",
       "legendFormat": "Total Received Routes"
      },
      {
       "expr": "sum(gnmic_sros_bgp_neighbors_sent{router_router_name=\"Base\"})",
       "legendFormat": "Total Sent Routes"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      {
       "expr": "gnmic_sros_mem_available_memory",
       "legendFormat": "Free"
      },
      { "expr": "gnmic_sros_mem_total_in_use", "legendFormat": "Utilization" },
      {
       "expr": "gnmic_sros_mem_current_total_size - gnmic_sros_mem_total_in_use",
       "legendFormat": "Reserved"
      }
     ]
    }
   ]
  },
  {
   "title": "Nokia SRL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Underlay OSPF Neighbors",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gnmic_srl_ospf_neighbors_neighbor_count{network_instance_name=\"default\", instance_name=\"default\", area_area_id=\"0.0.0.0\"})",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Overlay BGP Neighbors",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 3, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gnmic_srl_bgp_stats_total_peers{network_instance_name=\"default\"}",
       "legendFormat": "Total Peers"
      },
      {
       "expr": "gnmic_srl_bgp_stats_up_peers{network_instance_name=\"default\"}",
       "legendFormat": "Up Peers"
      }
     ]
    },
    {
     "title": "BGP Routes",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 6, "x": 9, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "gnmic_srl_bgp_stats_total_received_routes{network_instance_name=\"default\"}",
       "legendFormat": "Total Received Routes"
      },
      {
       "expr": "gnmic_srl_bgp_stats_total_active_routes{network_instance_name=\"default\"}",
       "legendFormat": "Total Active Routes"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "gnmic_srl_cpu_instant", "legendFormat": "Total" }
     ]
    },
    {
     "title": "OSPF Neighbors Uptime",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "gnmic_srl_ospf_uptime_up_time{network_instance_name=\"default\", instance_name=\"default\", area_area_id=\"0.0.0.0\"} / 100",
       "legendFormat": "{{neighbor_router_id}}"
      }
     ]
    },
    {
     "title": "Active Interfaces",
     "type": "state-timeline",
     "gridPos": { "h": 12, "w": 5, "x": 10, "y": 8 },
     "targets": [
      {
       "expr": "gnmic_srl_if_oper_state_oper_state",
       "legendFormat": "{{interface_name}}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      { "expr": "gnmic_srl_mem_free", "legendFormat": "Free" },
      { "expr": "gnmic_srl_mem_utilization", "legendFormat": "Utilization" },
      { "expr": "gnmic_srl_mem_reserved", "legendFormat": "Reserved" },
      { "expr": "gnmic_srl_mem_physical", "legendFormat": "Physical" }
     ]
    },
    {
     "title": "Trhoughput",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "gnmic_srl_if_traffic_rate_in_bps",
       "legendFormat": "{{interface_name}}:IN"
      },
      {
       "expr": "gnmic_srl_if_traffic_rate_out_bps",
       "legendFormat": "{{interface_name}}:OUT"
      }
     ]
    },
    {
     "title": "VXLAN Statistics",
     "type": "table",
     "gridPos": { "h": 7, "w": 9, "x": 15, "y": 18 },
     "targets": [
      {
       "expr": "gnmic_srl_vxlan_stats_destination_index",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "EVPN Route Type 3",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 0, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gnmic_srl_evpn_imet_valid_route{network_instance_name=\"default\"})",
       "legendFormat": "Valid Routes"
      },
      {
       "expr": "sum(gnmic_srl_evpn_imet_used_route{network_instance_name=\"default\"})",
       "legendFormat": "Used Routes"
      }
     ]
    },
    {
     "title": "EVPN Route Type 2",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 5, "x": 5, "y": 19 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gnmic_srl_evpn_mac_ip_valid_route{network_instance_name=\"default\"})",
       "legendFormat": "Valid Routes"
      },
      {
       "expr": "sum(gnmic_srl_evpn_mac_ip_used_route{network_instance_name=\"default\"})",
       "legendFormat": "Used Routes"
      }
     ]
    },
    {
     "title": "Active VXLAN Interfaces",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 5, "x": 10, "y": 20 },
     "targets": [
      {
       "expr": "gnmic_srl_vxlan_if_oper_state_oper_state",
       "legendFormat": "{{vxlan_interface_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Arista cEOS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overlay BGP Neighbors",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 7, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gnmic_ceos_bgp_stats_active{network_instance_name=\"default\"})",
       "legendFormat": "Total Peers"
      },
      {
       "expr": "count(gnmic_ceos_bgp_stats_installed{network_instance_name=\"default\"}) > 0",
       "legendFormat": "Up Peers"
      }
     ]
    },
    {
     "title": "BGP Routes",
     "type": "gauge",
     "gridPos": { "h": 7, "w": 7, "x": 7, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(gnmic_ceos_bgp_stats_sent{network_instance_name=\"default\"})",
       "legendFormat": "Total Sent Routes"
      },
      {
       "expr": "sum(gnmic_ceos_bgp_stats_installed{network_instance_name=\"default\"})",
       "legendFormat": "Total Active Routes"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      { "expr": "gnmic_ceos_cpu_loadAvg1m", "legendFormat": "Total" }
     ]
    },
    {
     "title": "Trhoughput",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "expr": "rate(gnmic_ceos_if_stats_in_octets[$__rate_interval])*8",
       "legendFormat": "{{interface_name}}:IN"
      },
      {
       "expr": "rate(gnmic_ceos_if_stats_out_octets[$__rate_interval])*8",
       "legendFormat": "{{interface_name}}:OUT"
      }
     ]
    },
    {
     "title": "Active Interfaces",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 5, "x": 9, "y": 10 },
     "targets": [
      {
       "expr": "gnmic_ceos_if_oper_state_oper_status",
       "legendFormat": "{{interface_name}}"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbits" } },
     "targets": [
      { "expr": "gnmic_ceos_mem_free", "legendFormat": "Free" },
      { "expr": "gnmic_ceos_mem_used", "legendFormat": "Utilization" },
      { "expr": "gnmic_ceos_mem_reserved", "legendFormat": "Reserved" },
      { "expr": "gnmic_ceos_mem_physical", "legendFormat": "Physical" }
     ]
    }
   ]
  }
 ]
}